/**
 *
 * @author Mehedi Hasan Hemel
 */
package bnccadmission;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

public class Admission extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    ResultSet rs1 = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    PreparedStatement pst2 = null;

    public Admission() {
        initComponents();
        showDate();
        showTime();
    }
   void showDate() {
        java.util.Date a = new java.util.Date();
        SimpleDateFormat s1 = new SimpleDateFormat("EEE,dd-MMM-YY");
        dateLab.setText(s1.format(a));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                java.util.Date a = new java.util.Date();
                SimpleDateFormat s1 = new SimpleDateFormat("HH:mm:ss");
                clockLab.setText(s1.format(a));
            }

        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        BtnDetails = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BtnNewAdmission = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BtnPrimarySelection = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnExam = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BtnResult = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BtnBack = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        Minimize = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Year = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        UID = new javax.swing.JTextField();
        PPP = new javax.swing.JTextField();
        FormNo = new javax.swing.JTextField();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        PPG = new javax.swing.JTextField();
        btnResponse = new rojeru_san.RSButton();
        Add = new rojeru_san.RSButton();
        Dept = new javax.swing.JComboBox<>();
        PhotoOK = new javax.swing.JCheckBox();
        UIDCopyOK = new javax.swing.JCheckBox();
        AppFeeOK = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Name = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        View1 = new rojeru_san.RSButton();
        jLabel26 = new javax.swing.JLabel();
        clockLab = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        dateLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackGround.setBackground(new java.awt.Color(204, 255, 204));
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(0, 102, 51));

        BtnDetails.setBackground(new java.awt.Color(0, 153, 51));
        BtnDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnDetailsMouseEntered(evt);
            }
        });
        BtnDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dash Board");
        BtnDetails.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 100, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResIMG/Details30.png"))); // NOI18N
        BtnDetails.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 50));

        BtnNewAdmission.setBackground(new java.awt.Color(0, 204, 51));
        BtnNewAdmission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnNewAdmissionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnNewAdmissionMouseEntered(evt);
            }
        });
        BtnNewAdmission.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("New Admission");
        BtnNewAdmission.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 110, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResIMG/admission30.png"))); // NOI18N
        BtnNewAdmission.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 50));

        BtnPrimarySelection.setBackground(new java.awt.Color(0, 153, 51));
        BtnPrimarySelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPrimarySelectionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnPrimarySelectionMouseEntered(evt);
            }
        });
        BtnPrimarySelection.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Primary Selection");
        BtnPrimarySelection.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 130, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResIMG/PrimarySelected30.png"))); // NOI18N
        BtnPrimarySelection.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 50));

        BtnExam.setBackground(new java.awt.Color(0, 153, 51));
        BtnExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnExamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnExamMouseEntered(evt);
            }
        });
        BtnExam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Examination");
        BtnExam.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 110, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResIMG/Exam30.png"))); // NOI18N
        BtnExam.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 50));

        BtnResult.setBackground(new java.awt.Color(0, 153, 51));
        BtnResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnResultMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnResultMouseEntered(evt);
            }
        });
        BtnResult.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Admin Options");
        BtnResult.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 130, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResIMG/Result30.png"))); // NOI18N
        BtnResult.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 50));

        BtnBack.setBackground(new java.awt.Color(0, 153, 51));
        BtnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnBackMouseEntered(evt);
            }
        });
        BtnBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Log Out");
        BtnBack.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 110, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResIMG/back30.png"))); // NOI18N
        BtnBack.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 40, 50));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResIMG/MainLogo.png"))); // NOI18N

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnNewAdmission, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnPrimarySelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnExam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel16)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnNewAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnPrimarySelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnExam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        BackGround.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        Minimize.setBackground(new java.awt.Color(255, 255, 255));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeMouseEntered(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("-");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout MinimizeLayout = new javax.swing.GroupLayout(Minimize);
        Minimize.setLayout(MinimizeLayout);
        MinimizeLayout.setHorizontalGroup(
            MinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MinimizeLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MinimizeLayout.setVerticalGroup(
            MinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10)
        );

        BackGround.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 30, -1));

        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Please Fill up the forms");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 50, 200, 19);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Admission");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(30, 10, 130, 32);

        BackGround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 850, 80));

        Year.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });
        Year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                YearKeyTyped(evt);
            }
        });
        BackGround.add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 120, 40));

        Email.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        BackGround.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 630, 40));

        UID.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        BackGround.add(UID, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 260, 40));

        PPP.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        PPP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PPPKeyTyped(evt);
            }
        });
        BackGround.add(PPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 180, 40));

        FormNo.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        FormNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FormNoKeyTyped(evt);
            }
        });
        BackGround.add(FormNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 100, 40));

        Female.setBackground(new java.awt.Color(204, 255, 204));
        Female.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        Female.setForeground(new java.awt.Color(0, 0, 0));
        Female.setText("Female");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });
        BackGround.add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 120, 40));

        Male.setBackground(new java.awt.Color(204, 255, 204));
        Male.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        Male.setForeground(new java.awt.Color(0, 0, 0));
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        BackGround.add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 120, 40));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Name              :");
        BackGround.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 110, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Form No         :");
        BackGround.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 110, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Phone No (Personal) :");
        BackGround.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 180, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Phone No(Guardian) :");
        BackGround.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 170, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("University ID :");
        BackGround.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 110, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Department   :");
        BackGround.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 110, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Email              :");
        BackGround.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 110, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Year                 :");
        BackGround.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 210, 110, -1));

        PPG.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        PPG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PPGKeyTyped(evt);
            }
        });
        BackGround.add(PPG, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 180, 40));

        btnResponse.setBackground(new java.awt.Color(0, 0, 0));
        btnResponse.setText("ALL");
        btnResponse.setColorHover(new java.awt.Color(255, 0, 0));
        btnResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponseActionPerformed(evt);
            }
        });
        BackGround.add(btnResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 110, 30));

        Add.setBackground(new java.awt.Color(0, 0, 0));
        Add.setText("Register");
        Add.setColorHover(new java.awt.Color(255, 0, 0));
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        BackGround.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 90, 30));

        Dept.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Select >", "Department of Business Administration", "Department of Business Studies", "Department of Real Estate", "Department of Tourism & Hospitality Management", "Department of Innovation & Entrepreneurship", "Department of Computer Science and Engineering", "Department of Software Engineering", "Department of Multimedia & Creative Technology (MCT)", "Department of General Educational Development", "Department of Environmental Science and Disaster Management", "Department of Computing and Information System", "Department of Information Technology & Management (ITM)", "Department of Electronics and Telecommunication Engineering", "Department of Textile Engineering", "Department of Electrical and Electronic Engineering", "Department of Architecture", "Department of Civil Engineering", "Department of Pharmacy", "Department of Nutrition and Food Engineering", "Department of Public Health", "Department of English", "Department of Law", "Department of Journalism & Mass Communication", "Department of Development Studies" }));
        Dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptActionPerformed(evt);
            }
        });
        BackGround.add(Dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 630, 40));

        PhotoOK.setBackground(new java.awt.Color(204, 255, 204));
        PhotoOK.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        PhotoOK.setForeground(new java.awt.Color(0, 0, 0));
        PhotoOK.setText("Passport Size Photo");
        BackGround.add(PhotoOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 180, 40));

        UIDCopyOK.setBackground(new java.awt.Color(204, 255, 204));
        UIDCopyOK.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        UIDCopyOK.setForeground(new java.awt.Color(0, 0, 0));
        UIDCopyOK.setText("University ID Card's Copy");
        BackGround.add(UIDCopyOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 210, 40));

        AppFeeOK.setBackground(new java.awt.Color(204, 255, 204));
        AppFeeOK.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        AppFeeOK.setForeground(new java.awt.Color(0, 0, 0));
        AppFeeOK.setText("Application Fee");
        BackGround.add(AppFeeOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, 190, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Recruitment Form Distribution Information");
        BackGround.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 520, -1));
        BackGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 500, 20));

        Name.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        BackGround.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 630, 40));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Gender           :");
        BackGround.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 110, -1));

        View1.setBackground(new java.awt.Color(0, 0, 0));
        View1.setText("Check");
        View1.setColorHover(new java.awt.Color(255, 0, 0));
        View1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View1ActionPerformed(evt);
            }
        });
        BackGround.add(View1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 630, 90, 30));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Time :");
        BackGround.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 40, 30));

        clockLab.setBackground(new java.awt.Color(255, 255, 255));
        clockLab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clockLab.setForeground(new java.awt.Color(0, 0, 0));
        clockLab.setText("clock");
        BackGround.add(clockLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 60, 30));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Date :");
        BackGround.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 40, 30));

        dateLab.setBackground(new java.awt.Color(255, 255, 255));
        dateLab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dateLab.setForeground(new java.awt.Color(0, 0, 0));
        dateLab.setText("date");
        BackGround.add(dateLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDetailsMouseClicked
        new DashBoard().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDetailsMouseClicked

    private void BtnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBackMouseClicked
        new Login().setVisible(true);
        this.setVisible(false);              // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackMouseClicked

    private void BtnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBackMouseEntered
        resetColor(BtnDetails);
        BtnNewAdmission.setBackground(new Color(0, 204, 51));
        resetColor(BtnPrimarySelection);
        resetColor(BtnExam);
        resetColor(BtnResult);
        setColor(BtnBack);
        Minimize.setBackground(new Color(222, 222, 222));          // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackMouseEntered

    private void BtnDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDetailsMouseEntered
        setColor(BtnDetails);
        BtnNewAdmission.setBackground(new Color(0, 204, 51));
        resetColor(BtnPrimarySelection);
        resetColor(BtnExam);
        resetColor(BtnResult);
        resetColor(BtnBack);
        Minimize.setBackground(new Color(222, 222, 222)); // TODO add your handling code here:
    }//GEN-LAST:event_BtnDetailsMouseEntered

    private void BtnNewAdmissionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNewAdmissionMouseEntered
        resetColor(BtnDetails);
        BtnNewAdmission.setBackground(new Color(0, 204, 51));
        resetColor(BtnPrimarySelection);
        resetColor(BtnExam);
        resetColor(BtnResult);
        resetColor(BtnBack);
        Minimize.setBackground(new Color(222, 222, 222));         // TODO add your handling code here:
    }//GEN-LAST:event_BtnNewAdmissionMouseEntered

    private void BtnPrimarySelectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrimarySelectionMouseEntered
        resetColor(BtnDetails);
        BtnNewAdmission.setBackground(new Color(0, 204, 51));
        setColor(BtnPrimarySelection);
        resetColor(BtnExam);
        resetColor(BtnResult);
        resetColor(BtnBack);
        Minimize.setBackground(new Color(222, 222, 222));         // TODO add your handling code here:
    }//GEN-LAST:event_BtnPrimarySelectionMouseEntered

    private void BtnExamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExamMouseEntered
        resetColor(BtnDetails);
        BtnNewAdmission.setBackground(new Color(0, 204, 51));
        resetColor(BtnPrimarySelection);
        setColor(BtnExam);
        resetColor(BtnResult);
        resetColor(BtnBack);
        Minimize.setBackground(new Color(222, 222, 222));          // TODO add your handling code here:
    }//GEN-LAST:event_BtnExamMouseEntered

    private void BtnResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResultMouseEntered
        resetColor(BtnDetails);
        BtnNewAdmission.setBackground(new Color(0, 204, 51));
        resetColor(BtnPrimarySelection);
        resetColor(BtnExam);
        setColor(BtnResult);
        resetColor(BtnBack);
        Minimize.setBackground(new Color(222, 222, 222));          // TODO add your handling code here:
    }//GEN-LAST:event_BtnResultMouseEntered

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setExtendedState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseEntered
        resetColor(BtnDetails);
        BtnNewAdmission.setBackground(new Color(0, 204, 51));
        resetColor(BtnPrimarySelection);
        resetColor(BtnExam);
        resetColor(BtnResult);
        resetColor(BtnBack);
        setColor(Minimize);        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseEntered

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);         // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        resetColor(BtnDetails);
        BtnNewAdmission.setBackground(new Color(0, 204, 51));
        resetColor(BtnPrimarySelection);
        resetColor(BtnExam);
        resetColor(BtnResult);
        resetColor(BtnBack);
        setColor(Minimize);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void BtnNewAdmissionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnNewAdmissionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnNewAdmissionMouseClicked

    private void BtnPrimarySelectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPrimarySelectionMouseClicked
        new PrimarySelection().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPrimarySelectionMouseClicked

    private void BtnExamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExamMouseClicked
        new Examination().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnExamMouseClicked

    private void BtnResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResultMouseClicked
        new AdminOptions().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnResultMouseClicked

    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        if (Male.isSelected()) {
            Female.setSelected(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_MaleActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed
        if (Female.isSelected()) {
            Male.setSelected(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleActionPerformed

    private void btnResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponseActionPerformed
        new ViewAllRegInfo().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnResponseActionPerformed

    private void DeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeptActionPerformed

    private void PPPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PPPKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_PPPKeyTyped

    private void PPGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PPGKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_PPGKeyTyped

    private void FormNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FormNoKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_FormNoKeyTyped

    private void YearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YearKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_YearKeyTyped

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        con = Connect.ConnectDB();
        if (FormNo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Candidate's Primary Form No", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Year.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Candidate's Year of admisssion", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (Name.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Candidate's Name", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (UID.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the University ID of Candidate", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (PPP.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Candidate's Phone No.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Gender
        String Gen;
        if (Male.isSelected()) {
            Gen = Male.getText();
        } else if (Female.isSelected()) {
            Gen = Female.getText();
        } else {
            JOptionPane.showMessageDialog(this, "Please Select Gender of Candidate", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Dept.getSelectedItem().equals("< Select >")) {
            JOptionPane.showMessageDialog(this, "Please Select the name of your department of University", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (PPG.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the Phone No. of Candidate's Guardian", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (Email.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter Candidate's Email Address", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            //Photo,ID,Fee
            String Photo;
            if (PhotoOK.isSelected()) {
                Photo = "OK";
            } else {
                Photo = "";
            }
            String UIDOK;
            if (UIDCopyOK.isSelected()) {
                UIDOK = "OK";
            } else {
                UIDOK = "";
            }
            String Fee;
            if (AppFeeOK.isSelected()) {
                Fee = "OK";
            } else {
                Fee = "";
            }
            //reg
            String sql = "insert into registration(FormNo,Name,UID,Department,Gender,PhoneNoPersonal,PhoneNoParents,EmailAddress,Year,Photo,IDCardCopy,RegistrationFee)values('" + FormNo.getText() + "','" + Name.getText() + "','" + UID.getText() + "','" + Dept.getSelectedItem() + "','" + Gen + "','" + PPP.getText() + "','" + PPG.getText() + "','" + Email.getText() + "','" + Year.getText() + "','" + Photo + "','" + UIDOK + "','" + Fee + "')";
            pst = con.prepareStatement(sql);
            pst.execute();
            //Finding RegNo for Primary selection
            String sqlForRegNo = "select * from registration where FormNo = ? and Year = ?";
            pst2 = con.prepareStatement(sqlForRegNo);
            pst2.setInt(1, Integer.parseInt(FormNo.getText()));
            pst2.setInt(2, Integer.parseInt(Year.getText()));
            rs = pst2.executeQuery();
            int Re=0;
            if (rs.next()) {
                Re = rs.getInt("RegistrationID");
                System.out.println(Re);
            }
            String PrimarySelectionSQL = "insert into primaryselection(RegistrationID,FormNo,Name,UID,Department,Gender,PhoneNoPersonal,PhoneNoParents,Email,Year)values('" + Re+ "','" + FormNo.getText() + "','" + Name.getText() + "','" + UID.getText() + "','" + Dept.getSelectedItem() + "','" +Gen+ "','" +PPP.getText()+ "','" +PPG.getText()+ "','" +Email.getText()+ "','" +Year.getText()+ "')";
            pst1= con.prepareStatement(PrimarySelectionSQL);
            pst1.execute();
            //Sucessful Message
            JOptionPane.showMessageDialog(this, "Thank you, Registeration Successful", "Recruitment", JOptionPane.INFORMATION_MESSAGE);

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        // Clear all Fields
        FormNo.setText("");
        Name.setText("");
        Email.setText("");
        UID.setText("");
        Year.setText("");
        PPP.setText("");
        PPG.setText("");
        Male.setSelected(false);
        Female.setSelected(false);
        PhotoOK.setSelected(false);
        UIDCopyOK.setSelected(false);
        AppFeeOK.setSelected(false);
        Dept.setSelectedItem("< Select >");
    }//GEN-LAST:event_AddActionPerformed

    private void View1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View1ActionPerformed
        new RegInfo().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_View1ActionPerformed
    void setColor(JPanel panel) {
        panel.setBackground(new Color(204, 0, 0));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(0, 153, 51));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton Add;
    private javax.swing.JCheckBox AppFeeOK;
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel BtnBack;
    private javax.swing.JPanel BtnDetails;
    private javax.swing.JPanel BtnExam;
    private javax.swing.JPanel BtnNewAdmission;
    private javax.swing.JPanel BtnPrimarySelection;
    private javax.swing.JPanel BtnResult;
    private javax.swing.JComboBox<String> Dept;
    private javax.swing.JTextField Email;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField FormNo;
    private javax.swing.JRadioButton Male;
    private javax.swing.JPanel Minimize;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField PPG;
    private javax.swing.JTextField PPP;
    private javax.swing.JCheckBox PhotoOK;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JTextField UID;
    private javax.swing.JCheckBox UIDCopyOK;
    private rojeru_san.RSButton View1;
    private javax.swing.JTextField Year;
    private rojeru_san.RSButton btnResponse;
    private javax.swing.JLabel clockLab;
    private javax.swing.JLabel dateLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
