/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bnccadmission;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author mehed
 */
public class RegInfo extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement pst1 = null;
    /**
     * Creates new form DashBoard
     */
    public RegInfo() {
        initComponents();
        showDate();
        showTime();
    }
   void showDate() {
        java.util.Date a = new java.util.Date();
        SimpleDateFormat s1 = new SimpleDateFormat("EEE,dd-MMM-YY");
        dateLab.setText(s1.format(a));
    }

    void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                java.util.Date a = new java.util.Date();
                SimpleDateFormat s1 = new SimpleDateFormat("HH:mm:ss");
                clockLab.setText(s1.format(a));
            }

        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Minimize = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Year = new javax.swing.JTextField();
        FormNo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        UID = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        PPG = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        PPP = new javax.swing.JTextField();
        Dept = new javax.swing.JComboBox<>();
        Gen = new javax.swing.JComboBox<>();
        PhotoOK = new javax.swing.JCheckBox();
        UIDOK = new javax.swing.JCheckBox();
        AppFeeOK = new javax.swing.JCheckBox();
        RegNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new rojeru_san.RSButton();
        btnSearch = new rojeru_san.RSButton();
        btnClear = new rojeru_san.RSButton();
        btnEdit = new rojeru_san.RSButton();
        btnUpdate = new rojeru_san.RSButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        clockLab = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        dateLab = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackGround.setBackground(new java.awt.Color(204, 255, 204));
        BackGround.setMinimumSize(new java.awt.Dimension(1100, 700));
        BackGround.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackGroundMouseEntered(evt);
            }
        });
        BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Confidential ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ResIMG/Logo100.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, 110));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Admission");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, -1));

        BackGround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1100, 110));

        Minimize.setBackground(new java.awt.Color(255, 255, 255));
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizeMouseEntered(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel10.setText("-");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout MinimizeLayout = new javax.swing.GroupLayout(Minimize);
        Minimize.setLayout(MinimizeLayout);
        MinimizeLayout.setHorizontalGroup(
            MinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MinimizeLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MinimizeLayout.setVerticalGroup(
            MinimizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10)
        );

        BackGround.add(Minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 30, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Personal Phone No    : ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Year                                :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("University ID                 :");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Form No                         :");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Gender                           :");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Department                  : ");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Guardian's Phone No : ");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Name                             : ");

        Year.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        FormNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("E-mail Address           :");

        UID.setEditable(false);
        UID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        Name.setEditable(false);
        Name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        PPG.setEditable(false);
        PPG.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        Email.setEditable(false);
        Email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        PPP.setEditable(false);
        PPP.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        Dept.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Select >", "Department of Business Administration", "Department of Business Studies", "Department of Real Estate", "Department of Tourism & Hospitality Management", "Department of Innovation & Entrepreneurship", "Department of Computer Science and Engineering", "Department of Software Engineering", "Department of Multimedia & Creative Technology (MCT)", "Department of General Educational Development", "Department of Environmental Science and Disaster Management", "Department of Computing and Information System", "Department of Information Technology & Management (ITM)", "Department of Electronics and Telecommunication Engineering", "Department of Textile Engineering", "Department of Electrical and Electronic Engineering", "Department of Architecture", "Department of Civil Engineering", "Department of Pharmacy", "Department of Nutrition and Food Engineering", "Department of Public Health", "Department of English", "Department of Law", "Department of Journalism & Mass Communication", "Department of Development Studies" }));
        Dept.setEnabled(false);

        Gen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Select >", "Male", "Female" }));
        Gen.setEnabled(false);

        PhotoOK.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PhotoOK.setText("Photograph");
        PhotoOK.setEnabled(false);

        UIDOK.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UIDOK.setText("University ID Photocopy");
        UIDOK.setEnabled(false);

        AppFeeOK.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AppFeeOK.setText("Application Fee");
        AppFeeOK.setEnabled(false);

        RegNo.setEditable(false);
        RegNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Registration No           :");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Recruit Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(PhotoOK)
                        .addGap(18, 18, 18)
                        .addComponent(UIDOK)
                        .addGap(18, 18, 18)
                        .addComponent(AppFeeOK)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FormNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(RegNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Dept, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(PPP, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(PPG))
                                    .addComponent(Gen, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UID, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(49, 49, 49))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(UID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PPP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel8))
                    .addComponent(PPG, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Gen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhotoOK)
                    .addComponent(UIDOK)
                    .addComponent(AppFeeOK))
                .addGap(24, 24, 24))
        );

        BackGround.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 780, 450));

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.setColorHover(new java.awt.Color(255, 0, 0));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        BackGround.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 110, 30));

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setText("Search");
        btnSearch.setColorHover(new java.awt.Color(255, 0, 0));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        BackGround.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, 110, 30));

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.setColorHover(new java.awt.Color(255, 0, 0));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        BackGround.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 110, 30));

        btnEdit.setBackground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Enable Edit");
        btnEdit.setColorHover(new java.awt.Color(255, 0, 0));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        BackGround.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 110, 30));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.setColorHover(new java.awt.Color(255, 0, 0));
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        BackGround.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 110, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Please Enter Form No. and Registration Year For  Search");
        BackGround.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 450, -1));
        BackGround.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 400, -1));

        clockLab.setBackground(new java.awt.Color(255, 255, 255));
        clockLab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clockLab.setForeground(new java.awt.Color(0, 0, 0));
        clockLab.setText("clock");
        BackGround.add(clockLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 60, 30));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Time :");
        BackGround.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 30));

        dateLab.setBackground(new java.awt.Color(255, 255, 255));
        dateLab.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dateLab.setForeground(new java.awt.Color(0, 0, 0));
        dateLab.setText("date");
        BackGround.add(dateLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 110, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Date :");
        BackGround.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.setExtendedState(JFrame.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        setColor(Minimize);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);         // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseClicked

    private void MinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeMouseEntered
        setColor(Minimize);        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeMouseEntered

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Admission().setVisible(true);
        this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            con = Connect.ConnectDB();
            
            String sql = "select * from registration where FormNo = ? and Year = ?";

            pst = con.prepareStatement(sql);

            if (FormNo.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Candidate's Primary Form No", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (Year.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Candidate's Year of admisssion", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            pst.setInt(1, Integer.parseInt(FormNo.getText()));
            pst.setInt(2, Integer.parseInt(Year.getText()));

            ResultSet rs = pst.executeQuery();
            
            
            //Gender,PhoneNoPersonal,PhoneNoParents,EmailAddress,Year,Photo,IDCardCopy,RegistrationFee
            if (rs.next()) {
                RegNo.setText(rs.getString("RegistrationID"));
                FormNo.setText(rs.getString("FormNo"));
                Name.setText(rs.getString("Name"));
                UID.setText(rs.getString("UID"));
                Dept.setSelectedItem(rs.getString("Department"));
                Gen.setSelectedItem(rs.getString("Gender"));
                PPP.setText(rs.getString("PhoneNoPersonal"));
                PPG.setText(rs.getString("PhoneNoParents"));
                Email.setText(rs.getString("EmailAddress"));
                if (rs.getString("Photo").equals("OK")) {
                    PhotoOK.setSelected(true);
                }
                if (rs.getString("IDCardCopy").equals("OK")) {
                    UIDOK.setSelected(true);
                }
                if (rs.getString("RegistrationFee").equals("OK")) {
                    AppFeeOK.setSelected(true);
                }
String Re = rs.getString("RegistrationID");System.out.println(Re);
            } else {
                JOptionPane.showMessageDialog(null, "Record Not Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } 
        
                   // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        RegNo.setText("");
        FormNo.setText("");
        Name.setText("");
        Email.setText("");
        UID.setText("");
        Year.setText("");
        PPP.setText("");
        PPG.setText("");
        Gen.setSelectedItem("< Select >");
        PhotoOK.setSelected(false);
        UIDOK.setSelected(false);
        AppFeeOK.setSelected(false);
        Dept.setSelectedItem("< Select >");   // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (RegNo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please search first and than try to edit", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        btnSearch.setEnabled(false);
        btnClear.setEnabled(false);
        btnEdit.setEnabled(false);
        btnBack.setEnabled(false);
        btnUpdate.setEnabled(true);
        Dept.setEnabled(true);
        Gen.setEnabled(true);
        PhotoOK.setEnabled(true);
        UIDOK.setEnabled(true);
        AppFeeOK.setEnabled(true);
        FormNo.setEditable(false);
        Year.setEditable(false);
        Name.setEditable(true);
        UID.setEditable(true);
        PPP.setEditable(true);
        PPG.setEditable(true);
        Email.setEditable(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            con = Connect.ConnectDB();
            String Form = String.valueOf(FormNo.getText());
            String Years = String.valueOf(Year.getText());

            //Photo,ID,Fee
            String Photo;
            if (PhotoOK.isSelected()) {
                Photo = "OK";
            } else {
                Photo = "";
            }

            String UIDDOK;
            if (UIDOK.isSelected()) {
                UIDDOK = "OK";
            } else {
                UIDDOK = "";
            }

            String Fee;
            if (AppFeeOK.isSelected()) {
                Fee = "OK";
            } else {
                Fee = "";
            }
            //Reg Update
            String sql = "update registration set RegistrationID = '" + RegNo.getText() + "',Name ='" + Name.getText() + "',UID ='" + UID.getText() + "',Department ='" + Dept.getSelectedItem() + "',Gender='" + Gen.getSelectedItem() + "',PhoneNoPersonal ='" + PPP.getText() + "',PhoneNoParents ='" + PPG.getText() + "' ,EmailAddress ='" + Email.getText() + "' ,Photo ='" + Photo + "' ,IDCardCopy ='" + UIDDOK + "' ,RegistrationFee ='" + Fee + "'  where FormNo ='" + Form + "' and Year ='" + Years + "'";
            pst = con.prepareStatement(sql);
            pst.executeUpdate();
            //Primaty Selection Update
            String sql1 = "update primaryselection set RegistrationID = '" + RegNo.getText() + "',Name ='" + Name.getText() + "',UID ='" + UID.getText() + "',Department ='" + Dept.getSelectedItem() + "',Gender='" + Gen.getSelectedItem() + "',PhoneNoPersonal ='" + PPP.getText() + "',PhoneNoParents ='" + PPG.getText() + "' ,Email ='" + Email.getText() + "' where FormNo ='" + Form + "' and Year ='" + Years + "'";
            pst1 = con.prepareStatement(sql1);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Successfully updated", "User info", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        AppFeeOK.setEnabled(false);
        PhotoOK.setEnabled(false);
        UIDOK.setEnabled(false);
        FormNo.setEditable(true);
        Year.setEditable(true);
        Name.setEditable(false);
        UID.setEditable(false);
        PPP.setEditable(false);
        PPG.setEditable(false);
        Email.setEditable(false);
        btnUpdate.setEnabled(false);
        Dept.setEnabled(false);
        btnSearch.setEnabled(true);
        btnClear.setEnabled(true);
        btnBack.setEnabled(true);
        btnEdit.setEnabled(true);
        Gen.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void BackGroundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackGroundMouseEntered
        resetColor(Minimize); // TODO add your handling code here:
    }//GEN-LAST:event_BackGroundMouseEntered

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        resetColor(Minimize);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered
    void setColor(JPanel panel) {
        panel.setBackground(new Color(204, 0, 0));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(255, 255, 255));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AppFeeOK;
    private javax.swing.JPanel BackGround;
    private javax.swing.JComboBox<String> Dept;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FormNo;
    private javax.swing.JComboBox<String> Gen;
    private javax.swing.JPanel Minimize;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField PPG;
    private javax.swing.JTextField PPP;
    private javax.swing.JCheckBox PhotoOK;
    private javax.swing.JTextField RegNo;
    private javax.swing.JTextField UID;
    private javax.swing.JCheckBox UIDOK;
    private javax.swing.JTextField Year;
    private rojeru_san.RSButton btnBack;
    private rojeru_san.RSButton btnClear;
    private rojeru_san.RSButton btnEdit;
    private rojeru_san.RSButton btnSearch;
    private rojeru_san.RSButton btnUpdate;
    private javax.swing.JLabel clockLab;
    private javax.swing.JLabel dateLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
